//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Country_ID { get; set; }
        public string CountryName { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
    }
}
